### ISSUE TITLE
Constantly Needs Restart in Unity Mod Manager 

### ISSUE THREAD

**Issue by PonkyVT** [alterasc/CombatRelief#5]
Haven't been able to get this to work in Pathfinder Wotr for some time now. Every time the mod menu opens now it says the "!!!" meaning the mod needs a restart, but no matter what I do it just is needing it constantly. I've uninstalled the mod, reinstalled it etc. Worked perfectly fine before I retook Drezen in the story, and then stopped completely after that.

**Comment by PonkyVT** [comment]
Also, all settings for the mod disappear as well of course, just adding that in

**Comment by xADDBx** [comment]
Could you post the log files Player.log and FullGameLog.txt from %userprofile%\AppData\LocalLow\Owlcat Games ?

**Comment by alterasc** [comment]
Yes, please provide game logs.

**Comment by alterasc** [comment]
Closing since no logs/reproduction steps are provided, and it all works for me.

If it happens again, please reopen this or create new one with more information.
